import { CheckScenario } from './base.check';

export const AUTH_AI_GENERATED: CheckScenario = {
  id: 'AUTH-001',
  name: 'AI Generated Police Report',
  description:
    'Simulates a police report that has been flagged as AI-generated by the extraction layer.',
  mockData: {
    claim: {
      claimNumber: 'C-2024-001',
      description: 'Minor fender bender',
      incidentDate: '2024-01-01',
    },
    documents: [
      {
        type: 'POLICE_REPORT',
        extractedData: {
          report_number: 'R123456',
          incident: { description: 'Vehicle collision...' },
          authenticity: {
            ai_generated: true,
            suspicious_elements: ['Perfect grammar', 'Generic layout'],
          },
        },
      },
    ],
  },
  expectedResult: {
    recommendation: 'REJECT',
    redFlags: ['AI-generated document detected'],
  },
};

export const AUTH_DEEPFAKE_PHOTO: CheckScenario = {
  id: 'AUTH-002',
  name: 'Deepfake Damage Photo',
  description: 'Simulates a damage photo with visual anomalies.',
  mockData: {
    claim: { description: 'Hit a pole' },
    documents: [
      {
        type: 'DAMAGE_PHOTO',
        extractedData: {
          image_quality: 'GOOD',
          damage_assessment: { damaged_areas: ['front_bumper'] },
          authenticity: {
            ai_generated: true,
            potential_manipulation: ['warped reflections', 'inconsistent lighting'],
          },
        },
      },
    ],
  },
  expectedResult: {
    recommendation: 'REJECT',
    redFlags: ['Potential deepfake/manipulated photo'],
  },
};

export const AUTH_DOC_TAMPERING: CheckScenario = {
  id: 'AUTH-003',
  name: 'Document Tampering Detected',
  description: 'Digital forensics detected signs of document manipulation (fonts, layers).',
  mockData: {
    claim: { description: 'Theft claim' },
    documents: [
      {
        type: 'REPAIR_QUOTATION',
        extractedData: {
          quotation_number: 'Q-999',
          authenticity: {
            potential_manipulation: ['Inconsistent fonts', 'Digital alteration traces'],
            suspicious_elements: ['Font mismatch in total amount'],
          },
        },
      },
    ],
  },
  expectedResult: {
    recommendation: 'REJECT',
    redFlags: ['Document manipulation detected', 'Inconsistent fonts'],
  },
};

export const AUTH_SCREEN_CAPTURE: CheckScenario = {
  id: 'AUTH-004',
  name: 'Screen Capture Detected',
  description: 'Evidence submitted is a photo of a screen, which is highly suspicious.',
  mockData: {
    claim: {},
    documents: [
      {
        type: 'DAMAGE_PHOTO',
        extractedData: {
          authenticity: {
            screen_capture: true,
            suspicious_elements: ['Moiré patterns detected', 'Device bezel visible'],
          },
        },
      },
    ],
  },
  expectedResult: {
    recommendation: 'INVESTIGATE',
    redFlags: ['Screen capture detected', 'Potential non-original evidence'],
  },
};
