import {
  AUTH_AI_GENERATED,
  AUTH_DEEPFAKE_PHOTO,
  AUTH_DOC_TAMPERING,
  AUTH_SCREEN_CAPTURE,
} from './auth_checks';
import {
  ID_GHOST_DRIVER,
  ID_UNAUTHORIZED_DRIVER,
  ID_MYKAD_MISMATCH,
  ID_UNDERAGE_DRIVER,
  ID_NRIC_DOB_MISMATCH,
  ID_NAME_NRIC_REPORT_MISMATCH,
} from './identity_checks';
import {
  VEH_KLON_CAR,
  VEH_CHASSIS_MISMATCH,
  VEH_EXPIRED_ROADTAX,
  VEH_PHANTOM,
  VEH_OWNER_MISMATCH,
  VEH_QUOTATION_VEHICLE_MISMATCH,
} from './vehicle_checks';
import {
  LOG_PHYSICS_MISMATCH,
  LOG_TIME_TRAVEL,
  LOG_METADATA_MISMATCH,
  LOG_GPS_MISMATCH,
  LOG_ENVIRONMENT_MISMATCH,
  LOG_WEATHER_MISMATCH,
  LOG_AIRBAG_MISMATCH,
  LOG_SIGNATURE_MISSING,
} from './logic_checks';

export const TRINITY_CHECKS = [
  AUTH_AI_GENERATED,
  AUTH_DEEPFAKE_PHOTO,
  AUTH_DOC_TAMPERING,
  AUTH_SCREEN_CAPTURE,
  ID_GHOST_DRIVER,
  ID_UNAUTHORIZED_DRIVER,
  ID_MYKAD_MISMATCH,
  ID_UNDERAGE_DRIVER,
  ID_NRIC_DOB_MISMATCH,
  ID_NAME_NRIC_REPORT_MISMATCH,
  VEH_KLON_CAR,
  VEH_CHASSIS_MISMATCH,
  VEH_EXPIRED_ROADTAX,
  VEH_PHANTOM,
  VEH_OWNER_MISMATCH,
  VEH_QUOTATION_VEHICLE_MISMATCH,
  LOG_PHYSICS_MISMATCH,
  LOG_TIME_TRAVEL,
  LOG_METADATA_MISMATCH,
  LOG_GPS_MISMATCH,
  LOG_ENVIRONMENT_MISMATCH,
  LOG_WEATHER_MISMATCH,
  LOG_AIRBAG_MISMATCH,
  LOG_SIGNATURE_MISSING,
];

export * from './base.check';
