from fpdf import FPDF
import tempfile
import os
from datetime import datetime

class PIAMConsentPDF(FPDF):
    def __init__(self, tenant_info=None):
        super().__init__()
        self.tenant_info = tenant_info or {}
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Draw top logo section area (Simulating the TUNE PROTECT style)
        self.set_fill_color(255, 255, 255)
        
        # Firm Info (Top Left Placeholder for Logo + Text)
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(180, 0, 0) # Dark red like the sample
        self.cell(0, 8, self.tenant_info.get('firmName', 'TRUE CLAIM INSIGHT').upper(), 0, 1, 'L')
        
        self.set_font('Helvetica', '', 8)
        self.set_text_color(0, 0, 0)
        address = self.tenant_info.get('firmAddress', 'Kuala Lumpur, Malaysia')
        self.multi_cell(0, 4, address, 0, 'L')
        
        info_line = f"Tel: {self.tenant_info.get('firmPhone', '+60 3-XXXX XXXX')}   Website: {self.tenant_info.get('firmWebsite', 'www.trueclaim.ai')}"
        self.cell(0, 4, info_line, 0, 1, 'L')
        
        self.ln(5)
        
        # Main Title Bar (Grey background)
        self.set_fill_color(40, 44, 52) # Darker grey/blue
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 12)
        self.cell(0, 10, '  CLAIMANT CONSENT & DISCLOSURE FORM / BORANG KEIZINAN & PEDEDAHAN TUNTUTAN', 0, 1, 'L', fill=True)
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by True Claim Insight AI', 0, 0, 'C')

    def draw_section_header(self, english, malay):
        self.ln(2)
        self.set_fill_color(220, 220, 220) # Light grey for section headers
        self.set_text_color(0, 0, 0)
        self.set_font('Helvetica', 'B', 10)
        text = f" {english} / {malay}"
        self.cell(0, 6, text.upper(), 0, 1, 'L', fill=True)
        self.ln(2)

    def add_field(self, label_en, label_bm, value, width=0):
        self.set_font('Helvetica', '', 9)
        self.set_text_color(80, 80, 80)
        label = f"{label_en}"
        self.cell(40, 6, label, 0, 0)
        
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(0, 0, 0)
        self.cell(5, 6, ":", 0, 0)
        self.cell(width if width > 0 else 0, 6, str(value), 0, 1)
        
        # Sub-label for BM
        self.set_y(self.get_y() - 1.5)
        self.set_font('Helvetica', 'I', 7)
        self.set_text_color(120, 120, 120)
        self.cell(40, 3, label_bm, 0, 1)
        self.ln(1)

    def draw_disclosure_box(self):
        self.set_font('Helvetica', '', 7.5)
        self.set_text_color(30, 30, 30)
        
        points = [
            ("Pursuant to Paragraph 5 of Schedule 9 of the Financial Services Act 2013, you are to disclose in this form, fully and faithfully all the facts which you know or ought to know, otherwise the claim assessment may be affected.",
             "Mengikut Perenggan 5 daripada Jadual 9 Akta Perkhidmatan Kewangan 2013, anda dikehendaki menyatakan dengan penuh dan benar butir-butir yang diminta dalam borang ini, jika tidak penilaian tuntutan mungkin terjejas."),
            ("I hereby verify that the details provided are true and accurate. I consent to the collection and processing of my biometric data (voice, facial patterns) for claim verification purpose.",
             "Saya dengan ini mengesahkan bahawa butiran yang diberikan adalah benar dan tepat. Saya membenarkan pengumpulan dan pemprosesan data biometrik saya (suara, corak muka) untuk tujuan pengesahan tuntutan.")
        ]
        
        y_start = self.get_y()
        for en, bm in points:
            self.set_x(15)
            self.multi_cell(0, 3.5, f"- {en}\n- {bm}", 0, 'L')
            self.ln(2)
        
        y_end = self.get_y()
        self.rect(10, y_start - 2, 190, y_end - y_start + 4)
        self.ln(4)

def generate_consent_form(data: dict) -> str:
    """
    Generates a structured, bilingual PIAM-regulated consent form.
    """
    adjuster_info = data.get('adjuster', {})
    pdf = PIAMConsentPDF(tenant_info=adjuster_info)
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # 1. Disclosures Notice
    pdf.draw_disclosure_box()

    # 2. Particulars of Claimant
    pdf.draw_section_header("Particulars of Claimant", "Butir-butir Pemohon")
    claimant = data.get('claimant', {})
    
    # Grid layout for claimant
    pdf.add_field("Name", "Nama", claimant.get('name', 'N/A'))
    pdf.add_field("Identity Card No.", "No. Kad Pengenalan", claimant.get('nric', 'N/A'))
    
    current_y = pdf.get_y()
    pdf.add_field("Phone No.", "No. Telefon", claimant.get('phone', 'N/A'))
    
    pdf.set_xy(110, current_y)
    pdf.add_field("Email", "E-mel", claimant.get('email', 'N/A'))
    
    # 3. Particulars of Claim / Vehicle
    pdf.draw_section_header("Particulars of Claim / Vehicle", "Butir-butir Tuntutan / Kenderaan")
    claim = data.get('claim', {})
    
    pdf.add_field("Claim Number", "No. Tuntutan", claim.get('claimNumber', 'N/A'))
    pdf.add_field("Policy Number", "No. Polisi", claim.get('policyNumber', 'N/A'))
    
    current_y = pdf.get_y()
    pdf.add_field("Regn. No.", "No. Pendaftaran", claim.get('vehiclePlate', 'N/A'))
    pdf.set_xy(110, current_y)
    pdf.add_field("Year Make", "Tahun Dibuat", claim.get('vehicleYear', 'N/A'))
    
    current_y = pdf.get_y()
    pdf.add_field("Make & Model", "Buatan & Model", f"{claim.get('vehicleMake', 'N/A')} {claim.get('vehicleModel', '')}")
    
    current_y = pdf.get_y()
    pdf.add_field("Engine No.", "No. Enjin", claim.get('engineNumber', 'N/A'))
    pdf.set_xy(110, current_y)
    pdf.add_field("Chassis No.", "No. Casis", claim.get('chassisNumber', 'N/A'))
    
    pdf.add_field("Incident Date", "Tarikh Kejadian", claim.get('incidentDate', 'N/A'))
    pdf.add_field("Incident Location", "Lokasi Kejadian", claim.get('location', 'N/A'))

    # 4. Biometric Analysis Indicator (AI results)
    pdf.draw_section_header("Biometric Analysis Indicator", "Penunjuk Analisis Biometrik")
    analysis = data.get('analysis', {})
    
    pdf.set_font('Helvetica', '', 9)
    pdf.multi_cell(0, 5, "This verification process utilized AI-driven behavioral analysis. Results are provided as supporting evidence for professional adjuster review.", 0, 'L')
    pdf.ln(2)
    
    current_y = pdf.get_y()
    pdf.add_field("AI Risk Score", "Skor Risiko AI", analysis.get('riskScore', 'PENDING'))
    pdf.set_xy(110, current_y)
    pdf.add_field("Confidence Level", "Tahap Keyakinan", f"{analysis.get('deceptionScore', 0) * 100:.2f}%")
    
    pdf.ln(10)

    # 5. Signatures
    pdf.ln(5)
    y = pdf.get_y()
    # Signature Boxes
    pdf.rect(10, y, 85, 35)
    pdf.rect(115, y, 85, 35)
    
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_xy(10, y + 36)
    pdf.cell(85, 5, "CLAIMANT SIGNATURE / TANDATANGAN PEMOHON", 0, 0, 'C')
    pdf.set_xy(115, y + 36)
    pdf.cell(85, 5, "ADJUSTER SIGNATURE / TANDATANGAN PENYELARAS", 0, 0, 'C')
    
    pdf.set_font('Helvetica', '', 7)
    pdf.set_xy(10, y + 41)
    pdf.cell(85, 4, f"Date / Tarikh: {datetime.now().strftime('%d/%m/%Y')}", 0, 0, 'C')
    pdf.set_xy(115, y + 41)
    pdf.cell(85, 4, f"Name: {adjuster_info.get('name', 'N/A')}", 0, 0, 'C')

    # Save
    with tempfile.NamedTemporaryFile(delete=False, suffix='.pdf') as tmp:
        tmp.close()
        pdf_path = tmp.name
    
    pdf.output(pdf_path)
    return pdf_path
