from fpdf import FPDF
import tempfile
import os
from datetime import datetime

def format_date_str(date_str):
    try:
        if not date_str or date_str == 'N/A': return 'N/A'
        clean_date = date_str.replace('Z', '+00:00')
        dt = datetime.fromisoformat(clean_date)
        return dt.strftime('%Y-%m-%d')
    except:
        return date_str

class PIAMConsentPDF(FPDF):
    def __init__(self, tenant_info=None):
        # Default A4, Portrait, mm
        super().__init__(orientation='P', unit='mm', format='A4')
        self.tenant_info = tenant_info or {}
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Draw top logo section area (Simulating the TUNE PROTECT style)
        self.set_fill_color(255, 255, 255)

        # Generated Date/Time (Top Right)
        self.set_font('Helvetica', 'I', 7)
        self.set_text_color(150, 150, 150)
        now_str = datetime.now().strftime('%d/%m/%Y %H:%M:%S')
        self.set_xy(150, 10)
        self.cell(50, 5, f"Generated: {now_str}", 0, 0, 'R')
        
        # Reset to Top Left for Firm Info
        self.set_xy(10, 10)
        
        # Firm Info (Top Left Placeholder for Logo + Text)
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(11, 116, 50)

        firm_name = self.tenant_info.get('firmName', 'TRUE CLAIM INSIGHT')
        if not firm_name or firm_name == 'N/A':
            firm_name = 'TRUE CLAIM INSIGHT'
            
        self.cell(0, 8, firm_name.upper(), 0, 1, 'L')
        
        self.set_font('Helvetica', '', 8)
        self.set_text_color(0, 0, 0)
        
        address = self.tenant_info.get('firmAddress', 'N/A')
        if not address or address == 'N/A':
            address = 'Kuala Lumpur, Malaysia'
        self.multi_cell(110, 4, address, 0, 'L')
        
        phone = self.tenant_info.get('firmPhone', 'N/A')
        if not phone or phone == 'N/A':
            phone = '(General Line)'
        
        self.set_x(10) # Align left with the address
        self.cell(0, 4, f"Tel: {phone}", 0, 1, 'L')
        
        self.ln(5)
        
        # Main Title Bar (Grey background)
        self.set_fill_color(40, 44, 52) # Darker grey/blue
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 11)
        self.cell(0, 10, '  CLAIMANT CONSENT & DISCLOSURE FORM / BORANG KEIZINAN & PENDEDAHAN TUNTUTAN', 0, 1, 'L', fill=True)
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        # self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by True Claim Insight AI', 0, 0, 'C')

    def draw_section_header(self, english, malay):
        self.ln(2)
        self.set_fill_color(220, 220, 220) # Light grey for section headers
        self.set_text_color(0, 0, 0)
        self.set_font('Helvetica', 'B', 10)
        text = f" {english} / {malay}"
        self.cell(0, 6, text.upper(), 0, 1, 'L', fill=True)
        self.ln(2)

    def add_field(self, label_en, label_bm, value, width=0):
        start_x = self.get_x()
        self.set_font('Helvetica', '', 9)
        self.set_text_color(80, 80, 80)
        label = f"{label_en}"
        self.cell(40, 6, label, 0, 0)
        
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(0, 0, 0)
        self.cell(5, 6, ":", 0, 0)
        self.cell(width if width > 0 else 0, 6, str(value), 0, 1)
        
        # Sub-label for BM
        self.set_y(self.get_y() - 1.5)
        self.set_x(start_x)
        self.set_font('Helvetica', 'I', 7)
        self.set_text_color(120, 120, 120)
        self.cell(40, 3, label_bm, 0, 1)
        self.ln(1)

    def draw_disclosure_box(self):
        self.set_font('Helvetica', '', 7.5)
        self.set_text_color(30, 30, 30)
        
        english_points = [
            "Pursuant to Paragraph 5 of Schedule 9 of the Financial Services Act 2013, you are to disclose in this form, fully and faithfully all the facts which you know or ought to know, otherwise the claim assessment may be affected.",
            "I acknowledge and consent that this interview session may be audio and/or video recorded for the purposes of claim investigation, verification, and record keeping.",
            "I authorise the insurer, adjuster, and their representatives to collect, use, disclose, and process my personal data for purposes relating to this claim, in accordance with the Personal Data Protection Act 2010.",
            "I understand that any false statement, misrepresentation, or non-disclosure of material facts may result in the claim being rejected, reduced, or voided.",
            "I hereby verify that the details provided are true and accurate. I consent to the collection and processing of my biometric data (voice, facial patterns) for claim verification purpose."
        ]

        malay_points = [
            "Mengikut Perenggan 5 Jadual 9 Akta Perkhidmatan Kewangan 2013, anda dikehendaki menyatakan dengan lengkap dan benar butir-butir yang diminta dalam borang ini; kegagalan berbuat demikian boleh menjejaskan penilaian tuntutan.",
            "Saya mengakui dan bersetuju bahawa sesi temu bual ini boleh dirakam dalam bentuk audio dan/atau video bagi tujuan siasatan, pengesahan, serta penyimpanan rekod tuntutan.",
            "Saya memberi kuasa kepada pihak penanggung insurans, pelaras, serta wakil mereka untuk mengumpul, menggunakan, mendedahkan dan memproses data peribadi saya bagi tujuan yang berkaitan dengan tuntutan ini selaras dengan Akta Perlindungan Data Peribadi 2010.",
            "Saya memahami bahawa sebarang kenyataan palsu, salah nyata, atau kegagalan mendedahkan fakta material boleh menyebabkan tuntutan ditolak, dikurangkan atau dibatalkan.",
            "Saya dengan ini mengesahkan bahawa semua butiran yang diberikan adalah benar dan tepat. Saya membenarkan pengumpulan dan pemprosesan data biometrik saya (seperti suara dan corak muka) bagi tujuan pengesahan tuntutan."
        ]
        
        y_start = self.get_y()
        
        # English Section
        for point in english_points:
            self.set_x(15)
            self.multi_cell(0, 3.5, f"- {point}", 0, 'L')
            self.ln(0.8)
            
        self.ln(2)

        # Malay Section
        self.set_font('Helvetica', 'I', 7.5) # Optional: Italicize Malay for visual distinction
        self.set_text_color(90, 90, 90)
        for point in malay_points:
            self.set_x(15)
            self.multi_cell(0, 3.5, f"- {point}", 0, 'L')
            self.ln(0.8)
        
        y_end = self.get_y()
        self.rect(10, y_start - 2, 190, y_end - y_start + 4)
        self.ln(4)

def generate_consent_form(data: dict) -> str:
    """
    Generates a structured, bilingual PIAM-regulated consent form.
    """
    adjuster_info = data.get('adjuster', {})
    pdf = PIAMConsentPDF(tenant_info=adjuster_info)
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # 1. Disclosures Notice
    pdf.draw_disclosure_box()

    # Extract claim data early
    claim = data.get('claim', {})

    # 2. Particulars of Claimant
    pdf.draw_section_header("Particulars of Claimant", "Butir-butir Pemohon")
    claimant = data.get('claimant', {})
    
    # Grid layout for claimant
    pdf.add_field("Name", "Nama", claimant.get('name', 'N/A'))
    pdf.add_field("Identity Card No.", "No. Kad Pengenalan", claimant.get('nric', 'N/A'))
    
    current_y = pdf.get_y()
    pdf.add_field("Phone No.", "No. Telefon", claimant.get('phone', 'N/A'))
    
    pdf.set_xy(110, current_y)
    pdf.add_field("Email", "E-mel", claimant.get('email', 'N/A'))
    
    # Policy Number moved here
    pdf.add_field("Policy Number", "No. Polisi", claim.get('policyNumber', 'N/A'))
    
    # 3. Particulars of Claim / Vehicle
    pdf.draw_section_header("Particulars of Claim / Vehicle", "Butir-butir Tuntutan / Kenderaan")
    
    pdf.add_field("Claim Number", "No. Tuntutan", claim.get('claimNumber', 'N/A'))
    
    current_y = pdf.get_y()
    pdf.add_field("Regn. No.", "No. Pendaftaran", claim.get('vehiclePlate', 'N/A'))
    pdf.set_xy(110, current_y)
    pdf.add_field("Year Make", "Tahun Dibuat", claim.get('vehicleYear', 'N/A'))
    
    current_y = pdf.get_y()
    make = claim.get('vehicleMake', 'N/A')
    model = claim.get('vehicleModel', '')
    make_model = f"{make} {model}".strip()
    if not make_model or make_model == 'N/A':
        make_model = 'N/A'
    pdf.add_field("Make & Model", "Buatan & Model", make_model)
    
    current_y = pdf.get_y()
    pdf.add_field("Engine No.", "No. Enjin", claim.get('engineNumber', 'N/A'))
    pdf.set_xy(110, current_y)
    pdf.add_field("Chassis No.", "No. Casis", claim.get('chassisNumber', 'N/A'))
    
    incident_date = format_date_str(claim.get('incidentDate', 'N/A'))
    pdf.add_field("Incident Date", "Tarikh Kejadian", incident_date)
    pdf.add_field("Incident Location", "Lokasi Kejadian", claim.get('location', 'N/A'))

    # 4. Signatures
    pdf.ln(5)
    y = pdf.get_y()
    # Signature Boxes
    pdf.rect(10, y, 85, 28)
    pdf.rect(115, y, 85, 28)
    
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_xy(10, y + 29)
    pdf.cell(85, 5, "CLAIMANT SIGNATURE / TANDATANGAN PEMOHON", 0, 0, 'C')
    pdf.set_xy(115, y + 29)
    pdf.cell(85, 5, "ADJUSTER SIGNATURE / TANDATANGAN PENYELARAS", 0, 0, 'C')
    
    pdf.set_font('Helvetica', '', 7)
    pdf.set_xy(10, y + 34)
    pdf.cell(85, 4, f"Date / Tarikh: {format_date_str(datetime.now().isoformat())}", 0, 0, 'C')
    pdf.set_xy(115, y + 34)
    adjuster_name = adjuster_info.get('name', 'N/A')
    pdf.cell(85, 4, f"Name / Nama: {adjuster_name}", 0, 0, 'C')

    # Save
    with tempfile.NamedTemporaryFile(delete=False, suffix='.pdf') as tmp:
        tmp.close()
        pdf_path = tmp.name
    
    pdf.output(pdf_path)
    return pdf_path
